status: true
dependencies:
  config:
    - commerce_order.commerce_order_item_type.donation
    - field.field.commerce_order_item.donation.field_donation
  module:
    - commerce_order
    - inline_entity_form
id: commerce_order_item.donation.default
targetEntityType: commerce_order_item
bundle: donation
mode: default
content:
  purchased_entity:
    type: entity_reference_autocomplete
    weight: -1
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
      match_limit: 10
    region: content
    third_party_settings: {  }
  quantity:
    type: commerce_quantity
    weight: 1
    region: content
    settings:
      step: '1'
      placeholder: ''
    third_party_settings: {  }
  unit_price:
    type: commerce_unit_price
    weight: 2
    settings:
      require_confirmation: true
    region: content
    third_party_settings: {  }
hidden:
  created: true
