status: true
dependencies:
  config:
    - field.field.user.user.commerce_remote_id
    - field.field.user.user.field_last_password_reset
    - field.field.user.user.field_password_expiration
    - field.field.user.user.field_profile_admin_notes
    - field.field.user.user.field_profile_alt_email
    - field.field.user.user.field_profile_birth_date
    - field.field.user.user.field_profile_dont_contact
    - field.field.user.user.field_profile_e_copies
    - field.field.user.user.field_profile_expire_issue
    - field.field.user.user.field_profile_family_id
    - field.field.user.user.field_profile_first_name
    - field.field.user.user.field_profile_gender
    - field.field.user.user.field_profile_inmate
    - field.field.user.user.field_profile_inmate_number
    - field.field.user.user.field_profile_last_contact_date
    - field.field.user.user.field_profile_last_name
    - field.field.user.user.field_profile_last_renew_date
    - field.field.user.user.field_profile_location
    - field.field.user.user.field_profile_member_expire_date
    - field.field.user.user.field_profile_member_notes
    - field.field.user.user.field_profile_member_start_date
    - field.field.user.user.field_profile_membership_control
    - field.field.user.user.field_profile_membership_status
    - field.field.user.user.field_profile_membership_type
    - field.field.user.user.field_profile_shared_notes
    - field.field.user.user.field_profile_ship_notes
    - field.field.user.user.field_profile_troth_name
    - field.field.user.user.field_profile_visibility
    - field.field.user.user.field_telephone_number
    - field.field.user.user.field_user_facebook_url
    - field.field.user.user.field_user_instagram_url
    - field.field.user.user.field_user_linkedin_url
    - field.field.user.user.field_user_twitter_url
    - field.field.user.user.user_picture
    - image.style.thumbnail
  module:
    - address
    - image
    - link
    - telephone
    - user
id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  account:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  current_pass:
    weight: 1
    region: content
    settings: {  }
    third_party_settings: {  }
  field_profile_alt_email:
    type: email_default
    weight: 6
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_profile_first_name:
    type: string_textfield
    weight: 2
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_profile_last_name:
    type: string_textfield
    weight: 3
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_profile_location:
    type: address_default
    weight: 7
    region: content
    settings: {  }
    third_party_settings: {  }
  field_profile_member_notes:
    type: string_textarea
    weight: 10
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
  field_profile_troth_name:
    type: string_textfield
    weight: 4
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_profile_visibility:
    type: boolean_checkbox
    weight: 9
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  field_telephone_number:
    type: telephone_default
    weight: 8
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  field_user_facebook_url:
    type: link_default
    weight: 11
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_user_instagram_url:
    type: link_default
    weight: 13
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_user_linkedin_url:
    type: link_default
    weight: 14
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_user_twitter_url:
    type: link_default
    weight: 12
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  language:
    weight: 16
    region: content
    settings: {  }
    third_party_settings: {  }
  mail:
    weight: 5
    region: content
    settings: {  }
    third_party_settings: {  }
  name:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  timezone:
    weight: 17
    region: content
    settings: {  }
    third_party_settings: {  }
  user_picture:
    type: image_image
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    third_party_settings: {  }
    weight: 15
    region: content
hidden:
  commerce_remote_id: true
  contact: true
  customer_profiles: true
  field_last_password_reset: true
  field_password_expiration: true
  field_profile_admin_notes: true
  field_profile_birth_date: true
  field_profile_dont_contact: true
  field_profile_e_copies: true
  field_profile_expire_issue: true
  field_profile_family_id: true
  field_profile_gender: true
  field_profile_inmate: true
  field_profile_inmate_number: true
  field_profile_last_contact_date: true
  field_profile_last_renew_date: true
  field_profile_member_expire_date: true
  field_profile_member_start_date: true
  field_profile_membership_control: true
  field_profile_membership_status: true
  field_profile_membership_type: true
  field_profile_shared_notes: true
  field_profile_ship_notes: true
  membership_join_profiles: true
  membership_renew_profiles: true
  notify: true
  pass: true
  path: true
  roles: true
  status: true
