status: false
dependencies:
  config:
    - core.entity_view_mode.user.compact
    - field.field.user.user.commerce_remote_id
    - field.field.user.user.field_last_password_reset
    - field.field.user.user.field_password_expiration
    - field.field.user.user.field_profile_admin_notes
    - field.field.user.user.field_profile_alt_email
    - field.field.user.user.field_profile_birth_date
    - field.field.user.user.field_profile_dont_contact
    - field.field.user.user.field_profile_e_copies
    - field.field.user.user.field_profile_expire_issue
    - field.field.user.user.field_profile_family_id
    - field.field.user.user.field_profile_first_name
    - field.field.user.user.field_profile_gender
    - field.field.user.user.field_profile_inmate
    - field.field.user.user.field_profile_inmate_number
    - field.field.user.user.field_profile_last_contact_date
    - field.field.user.user.field_profile_last_name
    - field.field.user.user.field_profile_last_renew_date
    - field.field.user.user.field_profile_location
    - field.field.user.user.field_profile_member_expire_date
    - field.field.user.user.field_profile_member_notes
    - field.field.user.user.field_profile_member_start_date
    - field.field.user.user.field_profile_membership_control
    - field.field.user.user.field_profile_membership_status
    - field.field.user.user.field_profile_membership_type
    - field.field.user.user.field_profile_shared_notes
    - field.field.user.user.field_profile_ship_notes
    - field.field.user.user.field_profile_troth_name
    - field.field.user.user.field_profile_visibility
    - field.field.user.user.field_telephone_number
    - field.field.user.user.field_user_facebook_url
    - field.field.user.user.field_user_instagram_url
    - field.field.user.user.field_user_linkedin_url
    - field.field.user.user.field_user_twitter_url
    - field.field.user.user.user_picture
    - image.style.thumbnail
  module:
    - address
    - datetime
    - image
    - layout_builder
    - link
    - options
    - user
id: user.user.compact
targetEntityType: user
bundle: user
mode: compact
content:
  user_picture:
    type: image
    weight: 0
    region: content
    settings:
      image_style: thumbnail
      image_link: content
    third_party_settings: {  }
    label: hidden
hidden:
  commerce_remote_id: true
  customer_profiles: true
  entity_print_view_epub: true
  entity_print_view_pdf: true
  entity_print_view_word_docx: true
  field_alternative_email: true
  field_birth_date: true
  field_date_last_contact: true
  field_dont_contact: true
  field_expire_date: true
  field_facebook_url: true
  field_first_name: true
  field_join_date: true
  field_last_name: true
  field_mailing_address: true
  field_password_expiration: true
  field_preferred_name: true
  field_status: true
  field_telephone_number: true
  field_visible: true
  mail: true
  member_for: true
  membership_join_profiles: true
  membership_renew_profiles: true
